/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_rheasalon;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class frmMenu extends javax.swing.JFrame {
private JPanel contentPanel;
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
      /**  initComponents();**/
        initComponent();
        
    }

    private void initComponent(){
        
    JMenuBar menuBar = new JMenuBar();
    JMenu menu = new JMenu("Menu");
    
    JMenuItem inventoryMenuItem = new JMenuItem("Inventory");
    inventoryMenuItem.addActionListener((java.awt.event.ActionEvent e) -> {
        showInventoryForm();
    });
    
    menu.add(inventoryMenuItem);
    menuBar.add(menu);
    setJMenuBar(menuBar);

    /*JMenuItem ServiceMenuItem = new JMenuItem("Service");
        ServiceMenuItem.addActionListener(new ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e) {
            showServiceForm();
        }
    });
    menu.add(ServiceMenuItem);
    menuBar.add(menu);
    setJMenuBar(menuBar);*/
    
    JMenuItem LogoutMenuItem = new JMenuItem("Logout");
    LogoutMenuItem.addActionListener((java.awt.event.ActionEvent e) -> {
            showLogout();
    });
    menu.add(LogoutMenuItem);
    menuBar.add(menu);
    setJMenuBar(menuBar);
    
    contentPanel = new JPanel();
    contentPanel.setLayout(new CardLayout());
    getContentPane().add(contentPanel, BorderLayout.CENTER);
    
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Main Menu");
    setSize(870,470);  
    setLocationRelativeTo(null);
    }
    
    private void showLogout(){
        
        this.setVisible(false);
        frmSignIn Login = new frmSignIn();
        Login.setVisible(true);
        Login.pack();
        Login.setLocationRelativeTo(null);
        
       /* JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to Logout", 
                "EXIT", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }   */ 
    }
    private void showInventoryForm() { 
    frmInventory inventoryForm = new frmInventory();
    contentPanel.removeAll();
    contentPanel.add(inventoryForm);
    contentPanel.repaint();
    contentPanel.revalidate();
    }

    /* private void showServiceForm() { 
    frmServices ServiceForm = new frmServices();
    contentPanel.removeAll();
    contentPanel.add(ServiceForm);
    contentPanel.repaint();
    contentPanel.revalidate(); 
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(870, 470));
        setResizable(false);
        setSize(new java.awt.Dimension(8500, 450));

        label2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label2.setText("Rhea Mercado Hair and Make-up Salon for Men & Women");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Inventory");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Logout");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6701, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
